sudo: required

language: generic

services:
  - docker

before_install:
  - echo "Start crating an image with dockerfile"
  - docker build -t choimingi/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true choimingi/docker-react-app npm run test -- -- coverage

after_success:
  - echo "Test success 2nd"
