sudo: required

language: generic

services:
  - docker

before_install:
  - echo "Start crating an image"
  - docker build -t mingi/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true mingi/docker-react-app npm run test -- -- coverage

after_success:
  - echo "Test success"
